### ISSUE TITLE
ACL CRUD management.

### ISSUE THREAD

**Issue by amcgregor** [bravecollective/core#12]
- [ ] Basic ACL CRUD views.
- [ ] Basic ACL CRUD actions.

**Comment by Byetsniv** [comment]
I'll try to get to work on the CRUD actions with some dirty views tonight (my time). Current thinking on ACLs is as follows, someone say something if you have better ideas, this is just my third draft of this:

A Permission object is a python dict() (hash table if you don't know python) as follows

``` python
{
  'type': 'user',   # or 'group' 
  'name': 'Byetsniv',
  'allowed': View # or Edit/Full or something else? More? we can define these constants somewhere.
}
```

Each "view"/page/feature will have an ACL, which is just a python list() of Permission objects.

Checking an ACL will simply be a matter of going through the list as follows:

``` python
def matches(user, perm):
  if perm['type'] == 'user':
    return perm['name'] == user.name
  if perm['type'] == 'group':
    return user.groups.contains(perm['name'])
  return False

def get_permission(current_user, ACL)
  for perm in ACL:
    if matches(current_user, group):
      return perm['allowed']
  return False
```

ACL operations then (in python) become list operations, relatively straight forward to manage. 

# Downsides:

Managing all ACLs might be cumbersome in terms of complexity. Looking up to see what Byetsniv is allowed to do will involve checking the ACL on each view/page. I don't think this is a real problem, as we shouldn't have too many views anyway, and it's hopefully not something people will do often.

# Questions I've considered:

## Should I write code so that permissions might be one of "None", "View", "Full"?

The two options I see are:
- Byetsniv has permission to access "ViewTopSecretThing", but does not have permission to access "EditTopSecretThing", or
- Byetsniv has the permission level "ViewOnly" to "TopSecretThing".

I've gone with the second. Consider the case where a user is loading a page of Inventory. If they have ViewOnly they should get a read-only page, whereas if they have Full permission they might be shown extra buttons. If I'd gone with the first option, I'd have to check for "ViewInventory" permission and "EditInventory" permission.

## Should we use constant variables rather than strings for comparators?

My code compares the strings 'user' and 'group' often.  I've noted that I'll make View and Full actual constants, but I'm not sold either way. Comparing constants should be faster. Maybe python enums? Personally I'm leaning towards constants or enums, but I'm a C++ coder so I'm not 100% how well we can do that in Python. Google has some solutions though.

Anyway, comments welcome, T-4 hours till I get anywhere near coding anything.

**Comment by amcgregor** [comment]
My thinking was that the ACL would be web-editable, and fairly rudimentary.  A basic "first rule to pass or fail returns" setup per ACL, with the purpose of the rules to automatically attach short tag-style identifiers to the account.  The goal of the ACLs are to use potentially secret information (that isn't revealed to applications) to determine which tags an application sees.

In this way, more finite permissions (such as read-only/read-write) could be implemented if the application desires them by using dot-notation partitioning of the tag namespace.  (e.g. 'wiki.read', 'wiki.moderate', etc.)  Big words, all over the page!  ;)

This is in opposition to classical ACLs, which protect resources and grant fine, and explicit permissions for actions based on user/group/role.  In our case all ACLs (relevant to an application) will be evaluated simultaneously to determine the tag set when performing authz of that application.  There should be the possibility for global tags (such as 'fc' or 'diplo') as well as application-specific (using dot-notation prefixes).

A declarative-style example in pPython:

``` python
class FleetCommander(ACL):
    tag = 'fc'
    global_ = True

    ruleset = [
            MemberInList(allow, [...]),  # allow for guest FCs
            MemberInAllianceHasTitle(allow, "BRAVE", "FC"),
            DenyAll()
        ]
```

The ACL entries would be MongoEngine Document instances (data-backed) and the rulesets would be described using EmbeddedDocument instances (again for data backing).  Actual validation would need to iterate global rules and rules of certain prefixes, and return the tags.

**Comment by Byetsniv** [comment]
> My thinking was that the ACL would be web-editable, and fairly rudimentary. A basic "first rule to pass or fail returns" setup per ACL, with the purpose of the rules to automatically attach short tag-style identifiers to the account. The goal of the ACLs are to use potentially secret information (that isn't revealed to applications) to determine which tags an application sees.

When you say "attach short tag-style identifiers", what does attach mean? Is that something that should actually be implemented, in that an core.adam.auth.User should have a tags field (or getTags() method)?
Or is that just a way of thinking about it, but not necessarily how it will be coded up?

> Actual validation would need to iterate global rules and rules of certain prefixes, and return the tags.

So is the idea to get all the (relevant) tags of the user, and then the application checks against these?

In my head, your proposal seems to go as follows

``` python
tags = user.getTags(application)   # Get the relevant tags
if 'wiki.read' in tags:
  userCanReadWiki = True
if 'admin' in tags:
  userCanReadWiki = True
```

I was thinking something more like

``` python
if user.hasPermission(application, ['wiki.read', 'admin']):   # only returns True if permission is found, and application is allowed to access that permission
  userCanReadWiki = True
```

Both of these cases are horribly over-simplified, but I hope you get the idea. I just feel like an application should be asking "Does this user have one of these permissions so I can let them do XYZ" rather than "Give me a list of this users permissions so I can see if I should let them do XYZ".

**Comment by amcgregor** [comment]
> When you say "attach short tag-style identifiers", what does attach mean? Is that something that should actually be implemented, in that an core.adam.auth.User should have a tags field (or getTags() method)?
> Or is that just a way of thinking about it, but not necessarily how it will be coded up?

It'd be the "short identifier" or "slug" of the ACL record/document.  Also, it more appropriately is tied to character rather than whole account (since authz bindings map `(user, character)` to `app`s.)

> So is the idea to get all the (relevant) tags of the user, and then the application checks against these?

Exactly.  Your p-code would effectively go in the client application.

During authz, the response to the application (upon successful authz) would simply include the list of slug strings, thus it only needs to happen once vs. multiple slow remote RPC calls to verify individual permissions, potentially several times during a single application request.
