### ISSUE TITLE
Provide support for Corporation keys across Core.

### ISSUE THREAD

**Issue by Acidity** [bravecollective/core#161]
Corporation keys are pretty much non-existent, and applications can neither require them nor request a specific token for corporation keys.

**Comment by jboning** [comment]
I'm curious for thoughts on how this should work. Strawman: If you have submitted a Corporation key, then you can authorize and revoke apps for access to that corporation.

I imagine we'll need to extend the API to allow apps to request corp access rather than character access. (Or does this already exist?)

**Comment by Acidity** [comment]
I think the best way to do this would be to have applications declare whether they want to accept corp keys or not when added, being able to choose from not at all, in addition to char keys, and only corp keys. When users authenticate the app, if they have a valid corp key on their account, and the app accepts them, it should be an option in the triangle menu where other characters go. I'm not sure if tokens currently distinguish between whether it's a character or corp token, but if not that would need to be added. I think that would cover most of the problems with corp keys; but a full review of the relevant code would probably be necessary as well.

This is just a thought though, and I haven't looked into this matter very thoroughly.
