### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by jboning** [bravecollective/core#245]
Idea for discussion: have core support some form of federation, where an account on one core instance allows you to log in to apps associated with another. The second instance would essentially be a client of the first, and would forward/proxy eve api requests.

The main benefit to doing this is that a user can enter an API key in one place, and have access to all related systems, instead of setting up a handful of different accounts and keys on allies' IT systems.

The main difficulty will be managing trust across instances. Ideally the admin of an instance could tune the degree of trust in a federated instance. Each instance will obviously want to compute groups/tags/permissions for itself (otherwise federated instances will need to have the same groups/permissions configured which would be a nightmare) based on eve api key metadata (key type and mask) and character info, all provided by the user's "home" instance. We'd probably want to add acl rules to control access based on the user's federation status (whether they're coming from a remote instance, and what that instance is). This would let an alliance could restrict its internal affairs groups to users for which it has keys directly, but allow users from other trusted instances to have access coalition-level groups (like alliedfc and blue).

**Comment by Acidity** [comment]
I've also been considering this topic as well, and your ideas on implementation of this are pretty much identical to what I was considering already, however, one of the issues with the federation that I've been thinking about resolving was how to have users sign in to a non-home Core instance. The method I'm leaning towards at the moment is for Core admins to indicate the domain name of each trusted instance (i.e. core.braveineve.com, auth.of-sound-mind.org, etc.) and users who wish to log in to another Core instance enter username@coreDomain and leave the password field blank (preferably with JS to prevent them from entering a password). This then redirects the user to their native Core instance login page to authenticate and authorize the new instance (in the same way applications are authorized). This way username conflicts across instances are a non-factor. 
The other issue I ran into was how to have instances manage the 'User' objects of non-native users. I see 2 main ways to handle this: 1.) the Native instance handles all application tokens, even those for applications not registered in that instance, or 2.) the non-native instance makes a FederatedUser object for all non-native users which contains the federated username, the federated token, and all application tokens. I'm personally leaning heavily towards method 2, though we'll probably want to employ duplicate account detection when this is rolled out so that users can merge their previously existing Native account to a federated account.
Also, since this will add several steps to the process, we'll almost definitely want to resolve the BadSignatureError #70.
